"""remove legacy file path

Revision ID: 31cf0fa759c3
Revises: c0cf1edc376b
Create Date: 2026-08-29 00:29:09.162207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cf0fa759c3'
down_revision: Union[str, Sequence[str], None] = 'c0cf1edc376b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
