"""add cloudinary fields to document

Revision ID: 4666310e9664
Revises: 5b48c49cf38e
Create Date: 2026-06-14 00:21:35.673391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4666310e9664'
down_revision: Union[str, Sequence[str], None] = '5b48c49cf38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('cloudinary_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'cloudinary_url')
    op.drop_column('documents', 'cloudinary_public_id')
    # ### end Alembic commands ###
