"""create document shares table

Revision ID: e37730b7a704
Revises: e72a16f9ce6a
Create Date: 2026-08-28 13:10:56.787728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37730b7a704'
down_revision: Union[str, Sequence[str], None] = 'e72a16f9ce6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('share_token', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_shares_id'), 'document_shares', ['id'], unique=False)
    op.create_index(op.f('ix_document_shares_share_token'), 'document_shares', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_shares_share_token'), table_name='document_shares')
    op.drop_index(op.f('ix_document_shares_id'), table_name='document_shares')
    op.drop_table('document_shares')
    # ### end Alembic commands ###
